server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/your-repo-on-github
           uri:  file:///home/marcos/Documents/repos/config-repo-demo
security:
  basic:
    enabled: true
  user:
    name: spring-demo
    password: pqntslc1$