server:
  port: ${PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
security:
  basic:
    enabled: true
  user:
      name: spring-demo
      password: pqntslc1$

#  server:
#    enable-self-preservation: true
#  instance:
#    hostname: localhost
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#spring:
 # cloud:
  #  config:
   #   username: lacasolana-sc
  
    #  password: pqntslc1$
      